"""Abstract interfaces for step 4: table comparison and reporting."""
from __future__ import annotations

from abc import ABC, abstractmethod

from lit_inspector.steps.data_extraction.schemas import ExtractedTable
from lit_inspector.steps.table_comparison.schemas import (
    EvaluationReport,
    TableComparisonResult,
)


class TableComparator(ABC):
    """Interface for comparing a student's table against model-generated tables."""

    @abstractmethod
    async def compare(
        self,
        student_table: ExtractedTable,
        model_tables: list[ExtractedTable],
    ) -> TableComparisonResult:
        """Compare a student table with one or more model-generated tables.

        Args:
            student_table: The student's submitted extraction.
            model_tables: Tables generated by different extractors.

        Returns:
            Comparison result with per-field diffs and agreement rate.
        """


class ReportGenerator(ABC):
    """Interface for generating a final evaluation report."""

    @abstractmethod
    async def generate(
        self,
        comparison_results: list[TableComparisonResult],
        run_id: str,
    ) -> EvaluationReport:
        """Generate a final evaluation report from comparison results.

        Args:
            comparison_results: Per-paper comparison results.
            run_id: Pipeline run identifier.

        Returns:
            Aggregated evaluation report.
        """
